name: Spike
description: Detect lag spikes and their causes
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.spike.SpikePlugin
depend: []
commands:
  spike:
    description: Admin interface
    permission: spike.spike
    usage: |-
      /spike reload - Reload configuration
      /spike generate [ticks] - Generate a lag spike
permissions:
  spike.spike:
    description: Use /spike
    default: op
