main: com.winthier.spike.SpikePlugin
name: Spike
description: Detect lag spikes and their causes
author: StarTux
version: 0.1
api-version: '1.21'
website: https://github.com/StarTux/Spike
depend: []
commands:
  spike:
    description: Admin interface
    permission: spike.spike
    usage: |-
      /spike reload - Reload configuration
      /spike generate <ticks> - Generate a lag spike
      /spike threshold <ticks> - Set reporting threshold
      /spike report - Dump lag spike report
      /spike last - Show last lag spike
permissions:
  spike.spike:
    description: Use /spike
    default: op
  spike.notify:
    description: Receive lag spike notifications
    default: false